language: java

jdk:
- oraclejdk8

install: true

script: |
  # only (attempt to) deploy non-pull request commits to the master branch or to tags
  if [[ "$TRAVIS_PULL_REQUEST" = false ]] && [[ "$TRAVIS_BRANCH" = master || ! -z "$TRAVIS_TAG" ]]; then
    mvn clean deploy
  else
    # otherwise, just run test suite
    mvn clean verify
  fi

after_success:
  # upload shaded JAR to S3
  sudo pip install awscli
  aws s3 cp --recursive --exclude "*" --include "*.jar" --exclude "r5-*" /home/travis/build/conveyal/r5/target s3://r5-builds

env:
  global:
  - secure: co/cnAH0EYVS68v81DCv5xwBizBAsiLrUMM/mI/H6np11bVFR4Pxc0yrfkOdoznf6kW/huyQMsCULHZDP2XnAb9jUR6MWZ6t8xhmOBDscSuTDmgQkrwefRc64mJkbA7xqndh1j71oLUqvKGQpc6IvlfHc0yyzIFwA9eNmAive9R5H1MGb7M21LNAXO4ALh9kAVJOSi48xOZ8fcoWm2tJ+RNbVHSguyAdKpHSWuu1UkaPE4mUshXx6ZQFskZLu8YhazkajzKff5mGziaqhAB8BInwXRzpvu+0bMAkz/eBSgyeAtZ9p21bC3s0F5DRAwrrk640Ejkg3aa8eGPQi1ufD0xY4lUZNsva9tgQgmXfhe0NYWH130tr4Tr/gY0EmmDLAa/CjK2Fs8Qe16bs1LnUfb4/Bj5apK1qiKqp+dJdxgEGCTPzLTl/3pSbL4mTGllIkt8rf91XDwEW9EMs0K5JjjpJJTnzSA/DeKUivSzib735/vW5JLsxWToI2ER0QdXoDek7yejnvapMadCh7MjF/Ectw0qBVrjB16DLQbxk/Q5wxm2ZnYshjCO1f2phja/c18UAnalWfqbWWGtRKDHYhwBaVsbaeeRBIC2vHPfc8KS7ZbuXNcmyNjDoSoviwPo73TAYNM8rIz+wM0hZkBiHxcPBJ5Ne3WLEX1SB9haBWBM=
  - secure: bgrdS1I9ByBYIB85ngcOoZ5DX8mLrEIg65xzHnzxSpFJ3xvd1VGMdjNZl2aO45+ghauxBJG3Q9INn5jdjllBkwjpv1MM1WF9vNLZQSGODjp1UFueBeLxtMzFm9PS/d58VLgofNnXMDDz4DG3ccqE+GjA6mWWuV1cr92Qj5jXgYcZXwGav/YY2J0erhgsOvkhYq05SqQyzHn+D2IL7hFaqI1Z2S4ygnoB3+TaI170f5rct7SWk0qItgsoE6d7KbW7z7gBzXGVOToSv7b7VMMAR/Fesw0DQYBudZaXe0pnjyNgIEwR60zUuDdwF2Z7UY1PLsdLfEW1V0IZIqkBTfqXBO5GnWLD8VAoi6eBvI1gnHeFLiHtN686RGOtsga/ghHovGWwGPgGTLStHkLA6UQRYJ6lHOftvqe/MXL2v1LiXeh1BjtRz01MPnYkP4jx1XFSmmJ21q9PAoNc1vZafqyjiXEg5S4641Y4YPHwARI03AjLEFKIgSJcoq5Np3K4tNqtao04u2uNQWew6zJznReJrdG1ALXlftPk2xddqRoGhZScAIRjtqEDXSCl66N1hlQ68QMW7+2eYMXcOywHCgik3BeZoXzaF3A12tifEe3R2iYWT6mJP9qHjEfx0Au7AgqFaVDjDR5xRaK79JQo57C/tf8QSciYPPth/eyBXB52wXo=

sudo: false

cache:
  directories:
  - $HOME/.m2/repository

notifications:
  slack: conveyal:vqrkN7708qU1OTL9XkbMqQFV
